# Generated by Django 5.0.4 on 2024-05-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.BooleanField(default=False),
        ),
    ]
