# Generated by Django 5.0.4 on 2024-05-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_question_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam',
            new_name='source',
        ),
    ]
